---

name: Setup arrakis.se SSH CA
description: Use the arrakis.se SSH CA to verify host certificates
author: Andreas Olsson

runs:
  using: composite
  steps:
    - name: Add SSH CA to /etc/ssh/ssh_known_hosts
      run: cat arrakis_ca_known_hosts | sudo tee --append /etc/ssh/ssh_known_hosts
      working-directory: ${{ github.action_path }}
      shell: bash
